[package]
name = "eds"
version = "0.1.0"
authors = ["avisrivastava <asrivastava@cs.stonybrook.edu>, Mike Love, Rob Patro"]
edition = "2018"

[dependencies]
pretty_env_logger = "0.3.0"
clap = "2.33.0"
log = "0.4.6"
byteorder = "1.3.1"
flate2 = "1.0.7"
libmath = "0.2.1"
